language: node_js

node_js:
  - "0.12"
  - "4.6.0"
  - "6.7.0"

before_install:
  - npm install --production
  - npm install mocha

env:
 - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libprotobuf-dev

sudo: false
